#pragma config(Sensor, S1,     FlipButton,     sensorNone)
#pragma config(Motor,  motorA,          flipmotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		// when the button is hit by the middle part
		if (SensorValue [FlipButton]) {
			setMotorSpeed(flipmotor, 0);
			sleep(1800);
			// move the bottom motor 170 degrees
			resetMotorEncoder(flipmotor);
			setMotorTarget(flipmotor, -170, 50);
			sleep(1000);
			// move the bottom motor back to its original area
			setMotorTarget(flipmotor, 0, 20);
			sleep(1000);
		}
	}
}
